# Generated by Django 5.1.5 on 2025-02-04 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('fixe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('proprio', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('valeur', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompteEnCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('frais_transaction', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compte_emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_emis', to='transaction.compte')),
                ('compte_recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_recus', to='transaction.compte')),
            ],
        ),
        migrations.CreateModel(
            name='DepenseTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.compte')),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='transaction.travail')),
            ],
        ),
        migrations.CreateModel(
            name='DepenseDetailTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depense', models.CharField(max_length=100)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('depense_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.depensetravail')),
            ],
        ),
        migrations.CreateModel(
            name='MontantPayeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.compte')),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avance_travail', to='transaction.travail')),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.compte')),
                ('depense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.depense')),
                ('depense_travail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.depensetravail')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('frais_transaction', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('avance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.montantpayetravail')),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.compte')),
                ('compte_en_compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.compteencompte')),
                ('depense_travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.depensetravail')),
                ('retrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.retrait')),
            ],
        ),
    ]
