# Generated by Django 5.1.1 on 2024-09-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='user_name',
            new_name='username',
        ),
    ]
