# Generated by Django 5.1.1 on 2024-09-06 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_destription_compte_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEnCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('compte_emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_emis', to='transaction.compte')),
                ('compte_recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_recus', to='transaction.compte')),
            ],
        ),
    ]
