# Generated by Django 5.1.1 on 2024-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_travail_montantpayetravail_depensetravail'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
