# Generated by Django 5.1.1 on 2024-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_travail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travail',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
