# Generated by Django 5.1.1 on 2024-09-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_depensetravail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensetravail',
            name='travail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='transaction.travail'),
        ),
        migrations.AlterField(
            model_name='montantpayetravail',
            name='travail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avance_travail', to='transaction.travail'),
        ),
    ]
