# Generated by Django 5.1.1 on 2024-09-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseDetailTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depense', models.CharField(max_length=100)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('depense_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.depensetravail')),
            ],
        ),
    ]
