# Generated by Django 5.1.1 on 2024-09-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_depensedetailtravail'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='montant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
