# Generated by Django 5.1.1 on 2024-10-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_depense_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteencompte',
            name='frais_transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
