# Generated by Django 5.1.1 on 2024-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_compteencompte_frais_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='frais_transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
