# Generated by Django 5.1.1 on 2024-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_operation_frais_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensetravail',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
