# Generated by Django 5.1.1 on 2024-10-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_depensetravail_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrait',
            name='depense_travail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.depensetravail'),
        ),
    ]
